Code standards updated to PHP 7.1
Codeception/module-db pull request #22
Opened 2021-05-10 18:19 UTC by TavoNiievez

- The minimum version of PHP is now 7.1
- Added strict types
- Added return types
- Added typehints
- Fix naming
- Removed unnecessary qualifiers

2021-05-12 19:35 UTC, Naktibalda requested changes

2021-05-12 19:35 UTC, Naktibalda commented on src/Codeception/Lib/Driver/Db.php
> +    public function load($sql): void
`$sql` is array of strings

2021-05-12 19:35 UTC, Naktibalda commented on src/Codeception/Lib/Driver/Db.php
> +    public function insert($tableName, array &$data): string
$tableName is string

2021-05-12 19:35 UTC, Naktibalda commented on src/Codeception/Lib/Driver/Db.php
> +    public function select($column, $table, array &$criteria): string
strings too.

2021-05-12 19:35 UTC, Naktibalda commented on src/Codeception/Lib/Driver/Db.php
> +    public function sqlLine($sql): bool
This $sql is string.

2021-05-12 19:35 UTC, Naktibalda commented on src/Codeception/Lib/Driver/Db.php
> +    public function getQuotedName($name): string
string

2021-05-12 19:35 UTC, Naktibalda commented on src/Codeception/Lib/Driver/Db.php
> +    public function update($table, array $data, array $criteria): string
all $table params are strings.

Some methods take $tableName, other take $table, maybe it would be better to pick one name.

2021-05-12 19:35 UTC, Naktibalda commented on src/Codeception/Lib/Driver/Db.php
> +    public function sqlQuery($query): void
string

2021-05-12 19:35 UTC, Naktibalda commented on src/Codeception/Lib/Driver/SqlSrv.php
> +    public function getQuotedName($name): string
And the same about all implementation specific drivers.

2021-05-27 21:10 UTC, TavoNiievez commented
@Naktibalda

2021-06-03 11:22 UTC, merged